import { promises as fs } from "fs";
import path from "path";
import { newId, type CanvasDoc, type DocPatch, type DocSummary, type Store } from "./types";

// Local dev store: one JSON file per doc under .data/docs/. Zero setup, persists
// across restarts. On Vercel the project filesystem is read-only, so fall back
// to /tmp just so a no-database preview boots — it's per-instance and ephemeral,
// so set DATABASE_URL for any real deploy (see lib/store/index.ts).
const ROOT = process.env.VERCEL ? "/tmp/agentic-canvas" : process.cwd();
const DIR = path.join(ROOT, ".data", "docs");

async function ensureDir() {
  await fs.mkdir(DIR, { recursive: true });
}

function file(id: string) {
  // id is generated by newId() (alphanumeric) — but guard against traversal.
  if (!/^[a-z0-9]+$/i.test(id)) throw new Error("bad id");
  return path.join(DIR, `${id}.json`);
}

async function read(id: string): Promise<CanvasDoc | null> {
  try {
    const doc = JSON.parse(await fs.readFile(file(id), "utf8")) as CanvasDoc;
    doc.files ??= {}; // older docs predate the files field
    return doc;
  } catch {
    return null;
  }
}

export function createFileStore(): Store {
  return {
    async create(title = "Untitled canvas") {
      await ensureDir();
      const now = new Date().toISOString();
      const doc: CanvasDoc = { id: newId(), title, scene: [], files: {}, chat: [], createdAt: now, updatedAt: now };
      await fs.writeFile(file(doc.id), JSON.stringify(doc), "utf8");
      return doc;
    },

    async get(id) {
      return read(id);
    },

    async list() {
      await ensureDir();
      const names = (await fs.readdir(DIR)).filter((n) => n.endsWith(".json"));
      const docs = await Promise.all(
        names.map((n) => read(path.basename(n, ".json"))),
      );
      return docs
        .filter((d): d is CanvasDoc => !!d)
        .map(({ id, title, createdAt, updatedAt }): DocSummary => ({ id, title, createdAt, updatedAt }))
        .sort((a, b) => (a.updatedAt < b.updatedAt ? 1 : -1));
    },

    async save(id, patch: DocPatch) {
      const doc = await read(id);
      if (!doc) throw new Error("not found");
      const next: CanvasDoc = {
        ...doc,
        ...(patch.title !== undefined ? { title: patch.title } : {}),
        ...(patch.scene !== undefined ? { scene: patch.scene } : {}),
        ...(patch.files !== undefined ? { files: patch.files } : {}),
        ...(patch.chat !== undefined ? { chat: patch.chat } : {}),
        updatedAt: new Date().toISOString(),
      };
      await fs.writeFile(file(id), JSON.stringify(next), "utf8");
    },

    async remove(id) {
      await fs.rm(file(id), { force: true });
    },
  };
}
